export type { User, Profile } from '@rayz/database'

// WebSocket Protocol Types
export {
  OpCode,
  GameCommandType,
  type ConnectionState,
  type DeviceRole,
  type GameState,
  type GameMode,
  type BaseClientMessage,
  type GetStatusMessage,
  type HeartbeatMessage,
  type ConfigUpdateMessage,
  type GameCommandMessage,
  type HitForwardMessage,
  type KillConfirmedMessage,
  type RemoteSoundMessage,
  type ClientMessage,
  type DeviceConfigStatus,
  type DeviceLiveStats,
  type DeviceLiveState,
  type DeviceStatusMessage,
  type HeartbeatAckMessage,
  type ShotFiredMessage,
  type HitReportMessage,
  type RespawnMessage,
  type ReloadMessage,
  type GameOverMessage,
  type AckMessage,
  type ServerMessage,
  type DeviceState,
  initialDeviceState,
} from './protocol'
